- name: "Remove Demo Inventory"
  awx.awx.inventory:
    controller_host: "{{ AWX_URL }}"
    controller_username: "{{ app_configs.awx.users.admin.username }}"
    controller_password: "{{ app_configs.awx.users.admin.password }}"
    name: "Demo Inventory"
    description: "Demo Inventory"
    organization: "{{ awx_slm_organization_name }}"
    state: absent

- name: "Remove Demo Project"
  awx.awx.project:
    controller_host: "{{ AWX_URL }}"
    controller_username: "{{ app_configs.awx.users.admin.username }}"
    controller_password: "{{ app_configs.awx.users.admin.password }}"
    name: "Demo Project"
    state: absent

- name: "Remove Demo Template Project"
  awx.awx.project:
    controller_host: "{{ AWX_URL }}"
    controller_username: "{{ app_configs.awx.users.admin.username }}"
    controller_password: "{{ app_configs.awx.users.admin.password }}"
    name: "Demo Job Template"
    state: absent
