### Inputs
- name: "MINIO | Assert inputs of 'minio/init | main.yml'"
  assert:
    that:
      - (MINIO_API_URL is defined) and (MINIO_API_URL|length > 0)           # URL of the Minio instance
      - (MINIO_CONSOLE_URL is defined) and (MINIO_CONSOLE_URL|length > 0)           # URL of the Minio instance
      - (CONSUL_SCHEME is defined) and (CONSUL_SCHEME|length > 0)   # Scheme of the Consul instance
      - (CONSUL_HOST is defined) and (CONSUL_HOST|length > 0)       # Host of the Consul instance
      - (CONSUL_PORT is defined)                                    # Port of the Consul instance
      - (_consul_token is defined) and (_consul_token|length > 0)   # Token to authenticate with Consul

- name: "MINIO | Get config"
  block:
    - name: "MINIO | Check if config exists in Consul"
      community.general.consul_kv:
        scheme: "{{ CONSUL_SCHEME }}"
        host: "{{ CONSUL_HOST }}"
        port: "{{ CONSUL_PORT }}"
        token: "{{ _consul_token }}"
        key: "config/minio/data"
      register: minio_config_consul

    - set_fact:
        minio_config: "{{ minio_config_consul.data.Value | from_yaml }}"
      when: minio_config_consul.data.Value is defined

    - name: "MINIO | Create Minio config"
      block:
        - name: "MINIO | Create admin password"
          set_fact:
            MINIO_ADMIN_PASSWORD: "{{ lookup('ansible.builtin.password', '/dev/null', chars=['ascii_lowercase', 'ascii_uppercase', 'digits'], length=24) }}"
          when: (MINIO_ADMIN_PASSWORD is not defined) or (MINIO_ADMIN_PASSWORD | default([]) | length == 0)

        - name: "MINIO | Update minio_config dictionary and override default values"
          set_fact:
            minio_config: "{{ minio_config | combine(
            { 'scheme': '{{ MINIO_SCHEME }}',
              'host': '{{ MINIO_HOST }}',
              'console-port': '{{ MINIO_CONSOLE_PORT }}',
              'api-port': '{{ MINIO_API_PORT }}',
              'users': {
                'admin': {
                  'username': 'admin',
                  'password': '{{ MINIO_ADMIN_PASSWORD }}'
                }            
              }
            }
        , recursive=true) }}"
        - name: "MINIO | Store Minio config in Consul"
          community.general.consul_kv:
            scheme: "{{ CONSUL_SCHEME }}"
            host: "{{ CONSUL_HOST }}"
            port: "{{ CONSUL_PORT }}"
            token: "{{ _consul_token }}"
            key: "{{ item.key }}"
            value: "{{ item.value }}"
          with_items:
            - { key: "config/minio/data", value: "{{ minio_config | to_yaml }}"  }
      when: minio_config_consul.data.Value is not defined

- name: "MINIO | Start Minio"
  block:
    - name: "MINIO | Create compose definition from template"
      set_fact:
        minio_compose: "{{ lookup('template', 'minio.yml') }}"
    - name: "MINIO | Start Minio containers"
      community.docker.docker_compose:
        project_name: eclipse-slm
        definition: "{{ minio_compose | from_yaml}}"
        state: present
        pull: true
      register: minio_compose_start_output
    - name: "MINIO | Wait for Minio being up"
      uri:
        url: "{{ MINIO_CONSOLE_URL }}"
        status_code: 200
      register: result
      until: result.status == 200
      retries: 120
      delay: 3


- name: "MINIO | Store resulting compose file"
  template:
    src: "minio.yml"
    dest: "{{ _store_compose_file }}"
  when: (_store_compose_file is defined) and (_store_compose_file|length > 0)

- name: "MINIO | Register Minio instance at Consul (discovery server)"
  include_role:
    name: consul/client
    tasks_from: register_service
  vars:
    _service_name: minio
    _service_port: "{{ MINIO_API_PORT }}"
    _service_address: "{{ MINIO_HOST }}"
    _http: "{{ MINIO_API_PORT }}/minio/health/live"
    _additional_tags:
      - "minio"

- name: "MINIO | Install Minio Client"
  include_tasks: config_minio.yml
  vars:
    _minio_root_user: "admin"
    _minio_root_password: "{{ MINIO_ADMIN_PASSWORD }}"
