- assert:
    that:
      - (keycloak_user is defined) and (keycloak_user|length > 0)

- name: "Assign realm roles to user '{{ keycloak_user.username }}'"
  include_role:
    name: "keycloak/keycloak_client"
    tasks_from: roles/assign_realm_role_to_user.yml
  with_items: "{{ keycloak_user.realmRoles }}"
  vars:
    username: "{{ keycloak_user.username }}"
    realm_role_name: "{{ item }}"
