- assert:
    that:
      - (keycloak_realms is defined) and (keycloak_realms|length > 0)

- name: "Create realms"
  include_role:
    name: "keycloak/keycloak_client"
    tasks_from: realms/create_realm.yml
  vars:
    keycloak_realm: "{{ item }}"
  with_items: "{{ keycloak_realms }}"

- set_fact:
    keycloak_realm: "{{ keycloak_realms[0].realm }}"
