- assert:
    that:
      - (keycloak_auth_url is defined) and (keycloak_auth_url|length > 0)
      - (keycloak_admin_username is defined) and (keycloak_admin_username|length > 0)
      - (keycloak_admin_username is defined) and (keycloak_admin_username|length > 0)

- name: "Get Keycloak admin access token"
  uri:
    url: "{{ keycloak_auth_url }}/realms/master/protocol/openid-connect/token"
    method: POST
    body_format: form-urlencoded
    body:
      username: "{{ keycloak_admin_username }}"
      password: "{{ keycloak_admin_password }}"
      grant_type: "password"
      client_id: "admin-cli"
    status_code: 200
    validate_certs: no
  register: output_keycloak_login

- set_fact:
    keycloak_access_token: "{{ output_keycloak_login.json.access_token }}"

