- name: "SLM | Create and store configs"
  include_tasks:
    file: "create_and_store_config.yml"
  vars:
    _app_name: "{{ item.app_name }}"
    scheme: "{{ item.scheme }}"
    host: "{{ item.host }}"
    port: "{{ item.port }}"
    consul_app_token: "{{ item.consul_app_token }}"
    database_host: "{{ item.database_host }}"
    database_port: "{{ item.database_port }}"
    database_user_username: "{{ item.database_user_username }}"
    database_schema: "{{ item.app_name }}"
  with_items:
    - app_name: service_management
      database_host: "{{ SERVICE_MANAGEMENT_DATABASE_HOST }}"
      database_port: "{{ SERVICE_MANAGEMENT_DATABASE_PORT }}"
      scheme: "{{ SERVICE_MANAGEMENT_SCHEME }}"
      host: "{{ SLM_HOSTNAME }}"
      port: "{{ SERVICE_MANAGEMENT_PORT | int }}"
      consul_app_token: "{{ CONSUL_MASTER_TOKEN }}"
    - app_name: resource_management
      database_host: "{{ RESOURCE_MANAGEMENT_DATABASE_HOST }}"
      database_port: "{{ RESOURCE_MANAGEMENT_DATABASE_PORT }}"
      scheme: "{{ RESOURCE_MANAGEMENT_SCHEME }}"
      host: "{{ SLM_HOSTNAME }}"
      port: "{{ RESOURCE_MANAGEMENT_PORT | int }}"
      consul_app_token: "{{ CONSUL_MASTER_TOKEN }}"
    - app_name: notification_service
      database_host: "{{ NOTIFICATION_SERVICE_DATABASE_HOST }}"
      database_port: "{{ NOTIFICATION_SERVICE_DATABASE_PORT }}"
      scheme: "{{ NOTIFICATION_SERVICE_SCHEME }}"
      host: "{{ SLM_HOSTNAME }}"
      port: "{{ NOTIFICATION_SERVICE_PORT | int }}"
      consul_app_token: "{{ CONSUL_MASTER_TOKEN }}"
    - app_name: catalog_service
      database_host: "{{ SLM_HOSTNAME }}"
      database_port: "{{ SLM_CATALOG_SERVICE_DATABASE_PORT }}"
      scheme: "{{ SLM_CATALOG_SERVICE_SCHEME }}"
      host: "{{ SLM_HOSTNAME }}"
      port: "{{ SLM_CATALOG_SERVICE_PORT | int }}"
      consul_app_token: "{{ CONSUL_MASTER_TOKEN }}"

- name: "Get Keycloak admin access token"
  include_role:
    name: keycloak/client
    tasks_from: authentication/get_admin_access_token.yml
- name: "Create Keycloak clients"
  include_role:
    name: "keycloak/client"
    tasks_from: clients/create_client.yml
  vars:
    _keycloak_access_token: "{{ keycloak_access_token }}"
    _keycloak_realm_name: "{{ KEYCLOAK_REALM }}"
    _keycloak_client: "{{ item }}"
  loop: "{{ keycloak_clients }}"

- name: "Create Vault app roles"
  include_role:
    name: vault/client
    tasks_from: create_approle_with_policies
  vars:
    _approle_name: "{{ item.name }}"
    _approle_policies: "{{ item.policies }}"
  loop: "{{ vault.approles }}"

- name: "Create Vault secret engine for AWX JWT Authenticator"
  include_role:
    name: vault/client
    tasks_from: create_kv_secret_engine
  vars:
    _kv_secret_engine_name: "{{ item }}"
  loop: "{{ vault.kv_secret_engines }}"

- name: "Start internal SLM components"
  block:
    - set_fact:
        slm_compose: "{{ lookup('template', 'slm.yml') }}"
    - name: "Start containers"
      community.docker.docker_compose:
        project_name: eclipse-slm
        definition: "{{ slm_compose | from_yaml}}"
        state: present
        pull: true

- name: "Store resulting compose file"
  template:
    src: "slm.yml"
    dest: "{{ _store_compose_file }}"
  when: (_store_compose_file is defined) and (_store_compose_file|length > 0)

- name: "Start SLM catalog"
  block:
    - set_fact:
        catalog_compose: "{{ lookup('template', 'catalog.yml') }}"
    - name: "Start containers"
      community.docker.docker_compose:
        project_name: eclipse-slm
        definition: "{{ catalog_compose | from_yaml }}"
        state: present
        pull: true

- name: "Store resulting compose file"
  template:
    src: "catalog.yml"
    dest: "{{ _store_compose_file }}"
  when: (_store_compose_file is defined) and (_store_compose_file|length > 0)




