slm:
  host: "{{ target_host }}"

keycloak:
  auth-server-url: "{{ keycloak_auth_server_url }}"

awx:
  url: "{{ awx_scheme }}://{{ awx_hostname }}:{{ awx_port }}"
  users:
    notification-service:
      username: "{{ awx_notification_service_username }}"
      password: "{{ awx_notification_service_password }}"
    resource-registry:
      username: "{{ awx_resource_management_username }}"
      password: "{{ awx_resource_management_password }}"
    service-registry:
      username: "{{ awx_service_management_username }}"
      password: "{{ awx_service_management_password }}"

consul:
  url: "{{ consul_scheme }}://{{ consul_hostname }}:{{ consul_port }}"
  master_token: "{{ consul_master_token }}"
  tokens:
    resource-registry: "{{ consul_resource_management_token }}"
    service-registry: "{{ consul_service_management_token }}"

vault:
  url: "{{ vault_scheme }}://{{ vault_hostname }}:{{ vault_port }}"
  root_token: "{{ vault_root_token }}"
  app-roles:
    resource-registry:
      role-id: "{{ vault_resource_management_app_role_id }}"
      secret-id: "{{ vault_resource_management_app_secret_id }}"
    service-registry:
      role-id: "{{ vault_service_management_app_role_id }}"
      secret-id: "{{ vault_service_management_app_secret_id }}"

notification-service:
  url: "http://{{ notification_service_host }}:{{ notification_service_port }}"
  database:
    host: {{ target_host }}
    port: 3301
    schema: {{ notification_service_database_schema }}
    username: {{ notification_service_database_user }}
    password: {{ notification_service_database_password }}

resource-registry:
  url: "http://{{ resource_management_host }}:{{ resource_management_port }}"
  database:
    host: {{ target_host }}
    port: 3310
    schema: {{ resource_management_database_schema }}
    username: {{ resource_management_database_user }}
    password: {{ resource_management_database_password }}

service-registry:
  url: "http://{{ service_management_host }}:{{ service_management_port }}"
  database:
    host: {{ target_host }}
    port: 3320
    schema: {{ service_management_database_schema }}
    username: {{ service_management_database_user }}
    password: {{ service_management_database_password }}
