### Inputs
- name: "Assert inputs of 'vault/client | create_approle_auth_method.yml'"
  assert:
    that:
      - (VAULT_URL is defined) and (VAULT_URL|length > 0)     # URL of the Vault instance
      - (_vault_token is defined) and (VAULT_URL|length > 0)  # Token to authenticate with Vault
    fail_msg: "Variable must be defined and not empty"

- name: "Create app role Auth Method 'approle'"
  uri:
    url: "{{ VAULT_URL }}/v1/sys/auth/approle"
    validate_certs: no
    method: POST
    headers:
      Authorization: "Bearer {{ _vault_token }}"
    body_format: json
    body:
      type: approle
    status_code: 204, 400 # 400 means auth method at path exists already
  register: output_create_approle
  changed_when: output_create_approle.status == 204
