### Inputs
- name: "Assert inputs of 'vault/client | create_policy.yml'"
  assert:
    that:
      - (VAULT_URL is defined) and (VAULT_URL|length > 0)
      - (_vault_token is defined) and (_vault_token|length > 0)
      - (_policy_name is defined) and (_policy_name|length > 0)
      - (_policy_content is defined) and (_policy_content|length > 0)
    fail_msg: "Variable must be defined and not empty"

- name: "Create policy '{{ _policy_name }}'"
  uri:
    url: "{{ VAULT_URL }}/v1/sys/policy/{{ _policy_name }}"
    validate_certs: no
    method: POST
    headers:
      Authorization: "Bearer {{ _vault_token }}"
    body_format: json
    body:
      policy: "{{ _policy_content }}"
    status_code: 204, 400 # 400 means policy at path exists already
  register: output_create_policy
  changed_when: output_create_policy.status == 204
