### Inputs
- name: "Assert inputs of 'vault/client | create_kv_secret_engine.yml'"
  assert:
    that:
      - (VAULT_URL is defined) and (VAULT_URL|length > 0)
      - (_vault_token is defined) and (_vault_token|length > 0)
      - (_kv_secret_engine_name is defined) and (_kv_secret_engine_name|length > 0)
    fail_msg: "Variable must be defined and not empty"

- name: "Create KV secret engine '{{ _kv_secret_engine_name }}'"
  uri:
    url: "{{ VAULT_URL }}/v1/sys/mounts/{{ _kv_secret_engine_name }}"
    validate_certs: no
    method: POST
    headers:
      Authorization: "Bearer {{ _vault_token }}"
    body_format: json
    body:
      type: kv
      description: "{{ kv_secret_engine_description| default('') }}"
      options:
        version: "{{ kv_secret_engine_version | default('2') }}"
    status_code: 204, 400
  register: output_create_kv_secret_engine
  changed_when: output_create_kv_secret_engine.status == 204
